/**
 * Textos centralizados extraídos de MongoDB
 * Última actualización: 2025-11-03
 * Total de textos: 127
 * 
 * Este archivo contiene todos los textos editados por la Dra. Sandra Vargas
 * en el sistema de administración y guardados en MongoDB.
 */

export const texts: { [key: string]: string } = {
  "about.approach.desc": "Integro herramientas de la terapia Gestalt, el enfoque sistémico y    el transpersonal adaptándolas a las necesidades y procesos únicos de cada persona",
  "about.approach.title": "Un enfoque integrativo",
  "about.badge.location": "Bogotá + Online Global",
  "about.cta.footer": "Online internacional • Presencial en Bogotá •",
  "about.example.gestalt": "Gestalt: \"¿Qué notas en tu cuerpo mientras hablas de esto? Dónde sientes esa emoción ahora?",
  "about.example.systemic": "Sistémico: \"¿En qué momento de tu historia aprendiste a relacionarte de esta manera?\"",
  "about.example.transpersonal": "Transpersonal: \"¿Qué mensaje o propósito más profundo podría tener esta vivencia para tu crecimiento?\"",
  "about.gestalt.desc": "Consciencia presente, contacto auténtico y responsabilidad personal",
  "about.how.apply.desc": "En cada sesión, integramos conscientemente estos enfoques según lo que necesites en ese momento. No es ecléctico ni improvisado: es una metodología coherente desarrollada a lo largo de años de experiencia y formación continua.",
  "about.how.apply.title": "¿Cómo lo aplico en mi práctica?",
  "about.integrative.title": "Más que técnicas, una metodología de vida",
  "about.intro": "La terapia no es sólo mi profesión, es mi camino de vida. Durante décadas he experimentado procesos de transformación profunda, que ahora entrego a mis consultantes. Mi práctica inició desde 1985 y se fundamenta en la empatía que nace de la experiencia vivida, el respeto profundo por tu historia única y un enfoque sistémico que aborda una mirada integral desde el contexto familiar y social, logrando  un acompañamiento que honra todas las dimensiones de tu ser.",
  "about.paragraph.1": "Durante décadas he sido participante activa en procesos terapéuticos profundos, tanto en Colombia como internacionalmente.  Ofrezco terapia individual y de pareja para hispanohablantes a nivel global y presencial en la ciudad de Bogotá.",
  "about.paragraph.2": "Mi trayectoria me ha permitido desarrollar un enfoque integrativo que combina Gestalt, Sistémica y Transpersonal.",
  "about.paragraph.3": "Esta intervención ha mostrado resultados a nivel individual en el camino del autoconocimiento, el desarrollo personal y el fortalecimiento de vínculos familiares y de pareja.",
  "about.result.desc": "No es sólo alivio de síntomas, es una evolución consciente; el despertar de tu potencial como ser humano integral\n",
  "about.subtitle.desc": "Un camino de vida dedicado a la transformación humana",
  "about.systemic.title": "Sistémica: Los vínculos que nos forman",
  "about.title": "Más de 38 años de experiencia en psicología clínica",
  "about.training.fhp.title": "Proceso Fischer Hoffman",
  "about.training.title": "Formación Especializada y Certificaciones",
  "about.what.integrative.desc": "Lo mejor de cada uno de los siguientes  enfoques de la psicología:",
  "about.what.integrative.title": "¿Qué es lo que se integra?",
  "contact.card.contact.title": "Contacto Psicóloga Bogotá",
  "contact.card.hours.sessions": "Horarios de citas:\n• Individual (75 min): Última cita 6:15 PM\n• Pareja (120 min): Última cita 5:30 PM\n• Mar/Sáb: Citas deben terminar antes 12:00 PM",
  "contact.card.hours.title": "Horario de Atención",
  "contact.card.hours.weekdays": "Lun, Mié, Jue, Vie: 7:30 AM - 7:30 PM",
  "contact.card.hours.weekend": "Mar, Sáb: 7:30 AM - 12:00 PM",
  "contact.modality.presencial.item.4": "• Ambiente cómodo y privado",
  "contact.process.title": "✨ Proceso de Agendamiento de Cita",
  "contact.title": "Agendar Cita Psicóloga Bogotá",
  "experience.description": "Una trayectoria excepcional en psicología clínica, desarrollo empresarial, facilitación internacional y programas de transformación humana. Desde Naciones Unidas hasta empresas multinacionales, creando programas propios y transformando vidas en Colombia, España, México y más países de Latinoamérica.",
  "experience.highlight.facilitator.achievement.1": "Programas de desarrollo personal y liderazgo ",
  "experience.highlight.facilitator.achievement.2": "Facilitación en México, Colombia, Estados Unidos, Lationamérica",
  "experience.highlight.facilitator.achievement.3": "Más de 23 años de experiencia internacional",
  "experience.highlight.facilitator.description": "Desarrollo personal con mujeres y hombres en empresa multinacional México y América\n",
  "experience.highlight.programs.title": "Creadora de programas propios",
  "experience.highlights.title": "Logros y experiencias destacadas",
  "experience.institutions.title": "Instituciones y Organizaciones Principales",
  "experience.stats.countries.number": "+25",
  "experience.stats.facilitating.description": "Talleres propios desde 2000",
  "experience.stats.facilitating.number": "+25",
  "experience.stats.institutions.number": "+10",
  "experience.timeline.1990.title": "Psicóloga Clínica y Educativa",
  "experience.timeline.2003.description": "Conducción de seminarios y talleres internacionales para el desarrollo personal y de liderazgo en diferentes países de América ",
  "experience.timeline.2003.year": "2017 - Actual y 2003 - 2012",
  "experience.timeline.2012.title": "Gestora Programa Liderazgo Ardyss",
  "experience.timeline.2017.description": "28 años de practica terapéutica en consultorio privado",
  "experience.timeline.2017.title": "Terapeuta integrativa ",
  "experience.timeline.2017.year": "1998 - Actual",
  "experience.timeline.title": "Trayectoria profesional",
  "experience.timeline.1988.description": "Evaluación y/o apoyo a poblaciones vulnerables, niños, jóvenes y adultos.",
  "experience.timeline.1988.location": "Universidad Nacional sede Bogotá",
  "experience.timeline.1988.title": "Facultad Medicina área Psiquiatría",
  "experience.timeline.1988.year": "1988 - 1990",
  "experience.title": "Más de 38 Años de Experiencia Profesional",
  "footer-copyright": "© 2026 Sandra Vargas Psicóloga. Todos los derechos reservados. Psicóloga especializada en terapia individual y de pareja con 38 años de experiencia en Bogotá.",
  "hero.badge": "Psicóloga Clínica Especializada",
  "hero.badge.integrative.title": "Enfoque Integrativo",
  "hero.badge.specialized.title": "Atiende adultos desde los 19 años",
  "hero.cta.primary": "Agendar Cita Online o Presencial",
  "hero.cta.secondary": "Contáctame por WhatsApp",
  "hero.description": "Psicóloga clínica   que  aplica un enfoque integrativo considerando a sus consultantes desde todos los aspectos:  a nivel físico, emocional, mental, espiritual y social ofreciendo un abordaje profundo y transformador.  Ofrece atención online global, en Español y presencial en consultorio privado en Bogotá",
  "hero.differentiator.local.title": "Consultorio Privado Bogotá",
  "hero.subtitle": "Psicóloga Clínica en Bogotá",
  "hero.subtitle2": "Enfoque Integrativo • Online Global + Presencial Bogotá",
  "hero.title": "Sandra Margarita Vargas",
  "hero-cta-primary": "Agendar Cita Online o Presencial",
  "hero-cta-secondary": "Contáctame por WhatsApp",
  "hero-description": "Psicóloga clínica especializada en adultos con enfoque integrativo holístico que combina Gestalt, sistémico y transpersonal. Transformando vidas a través de un proceso personal profundo con atención online global en español y presencial en consultorio privado en Bogotá.",
  "hero-subtitle": "Enfoque Integrativo • Online Global + Presencial Bogotá",
  "hero-title": "Sandra M. Vargas - Psicóloga Clínica en Bogotá",
  "logo-subtext": "Psicóloga Clínica",
  "logo-text": "Sandra Vargas",
  "nav-agendar": "Agendar",
  "nav-escribir": "Escribir",
  "nav-experiencia": "Experiencia",
  "nav-inicio": "Inicio",
  "nav-servicios": "Servicios",
  "nav-sobre-mi": "Sobre Mí",
  "online.badge": "Terapia en español para el mundo",
  "online.description": "Tu transformación personal no tiene fronteras. Accede a terapia especializada desde cualquier país del mundo, en la comodidad de tu hogar y horarios adaptados a tu zona horaria. La misma calidad y profundidad del consultorio presencial, ahora disponible de manera global para hispanohablantes.",
  "online.features.confidential.description": "Sesiones privadas y seguras desde cualquier lugar del mundo",
  "online.features.schedule.description": "Horarios flexibles adaptados a diferentes zonas horarias",
  "online.testimonial.spain": "Las sesiones online desde España han sido transformadoras. Sandra logra crear un espacio de confianza a pesar de la distancia.",
  "online.title": "Terapia Online Global en Español",
  "online.cta.title": "¿Listo para Comenzar tu Terapia Online?",
  "online.advantage.payment.description": "Métodos de pago adaptados a diferentes países: transferencias, Western Union, y otros sistemas internacionales.",
  "online.testimonial.mexico.text": "Como pareja colombiana viviendo en EE.UU., encontrar terapia en español de calidad era difícil. Sandra nos ayudó a encontrar herramientas para manejar diferentes soluciones.",
  "services.cta.couple.title": "Terapia de Pareja",
  "services.cta.individual.title": "Terapia Individual",
  "services.description": "Amplia experiencia en terapia individual adultos y terapia de pareja con enfoque integrativo que combina sistémico y Gestalt. Atención online internacional en español y sesiones presenciales en consultorio privado Bogotá.",
  "services.modalities.online": "• Online para hispanohablantes en todo el mundo",
  "services.modalities.presencial": "• Presencial en consultorio privado en Bogotá",
  "services.modalities.title": "Modalidades de Atención:",
  "services.title": "Servicios especializados para adultos",
  "services.individual.title": "Terapia individual adultos",
  "services.individual.solutions.title": "Beneficios que obtendrás:",
  "services.individual.problems.footer": "Si has experimentado alguna de estas situaciones, el proceso que construiremos juntos puede ayudarte a encontrar soluciones profundas y duraderas.",
  "services.individual.description": "",
  "services.couple.title": "Terapia de pareja",
  "services.couple.solutions.title": "Beneficios que obtendrán:",
  "services.couple.problems.footer": "Si has experimentado alguna de estas situaciones, durante el proceso terapéutico se construirán espacios que facilitarán soluciones y decisiones que mejorarán su calidad de vida",
  "services.couple.benefits.3": "Fortalecimiento del vínculo emocional",
  "services.couple.approach.description": "Trabajo con parejas en diferentes etapas de su relación, desde el fortalecimiento del vínculo hasta la resolución de conflictos profundos. Mi enfoque sistémico y gestáltico permite abordar tanto los patrones relacionales como las dinámicas emocionales.",
  "services.couple.approach.title": "Mi Enfoque en Terapia de Pareja",
  "services.couple.description": "Acompañamiento profesional para parejas que buscan fortalecer su relación, resolver conflictos o redefinir su vínculo. Un espacio seguro para trabajar juntos hacia una relación más saludable y consciente.",
  "services.office.desc": "Presencial",
  "services.individual.benefits.title": "Beneficios de la Terapia Individual:",
  "terapiaIndividual.approach.description": "Mi enfoque integrativo combina la terapia Gestalt (consciencia del presente), el enfoque sistémico (comprensión de tus vínculos) y la perspectiva transpersonal (conexión con tu propósito más profundo).",
  "terapiaIndividual.approach.title": "Mi Enfoque Terapéutico",
  "terapiaIndividual.cta.schedule": "Agendar Primera Sesión",
  "terapiaIndividual.cta.whatsapp": "Consultar por WhatsApp",
  "terapiaIndividual.description": "Acompañamiento profesional especializado para adultos que buscan autoconocimiento, sanación emocional y transformación personal a través de un proceso terapéutico profundo y consciente.",
  "terapiaIndividual.seo.description": "Terapia individual para adultos en Bogotá con Sandra Vargas, psicóloga clínica con 38 años de experiencia. Enfoque integrativo Gestalt, sistémico y transpersonal. Sesiones presenciales y online.",
  "terapiaIndividual.seo.title": "Terapia Individual para Adultos - Sandra Vargas Psicóloga Bogotá",
  "terapiaIndividual.sessions.description": "Cada sesión es un espacio de 75 minutos donde trabajaremos juntos en tu proceso personal con presencia, empatía y profesionalismo.",
  "terapiaIndividual.sessions.duration": "Duración: 75 minutos",
  "terapiaIndividual.sessions.modality.online": "Online: Para hispanohablantes en cualquier parte del mundo",
  "terapiaIndividual.sessions.modality.presencial": "Presencial: Consultorio privado en Bogotá",
  "terapiaIndividual.sessions.title": "¿Cómo son las sesiones?",
  "terapiaIndividual.title": "Terapia Individual para Adultos",
  "terapiaIndividual.whenToSeek.title": "¿Cuándo buscar terapia individual?",
  "terapiaIndividual.workWith.description": "Trabajo especialmente con adultos que buscan:\n\n• Autoconocimiento y desarrollo personal profundo\n• Sanación de heridas emocionales y traumas\n• Superación de ansiedad, depresión o crisis existenciales\n• Mejora de relaciones interpersonales y familiares\n• Procesos de duelo y cambios vitales importantes\n• Conexión con propósito de vida y sentido existencial",
  "terapiaIndividual.workWith.title": "¿Con quién trabajo?",
  "terapiaPareja.approach.description": "Utilizo un enfoque sistémico que nos permite comprender los patrones relacionales, combinado con herramientas gestálticas para trabajar la comunicación y el contacto auténtico entre ustedes.",
  "terapiaPareja.approach.title": "Mi Enfoque en Terapia de Pareja",
  "terapiaPareja.cta.schedule": "Agendar Primera Sesión de Pareja",
  "terapiaPareja.cta.whatsapp": "Consultar por WhatsApp",
  "terapiaPareja.description": "Acompañamiento profesional para parejas que desean fortalecer su vínculo, resolver conflictos, mejorar su comunicación o transitar momentos difíciles de su relación con apoyo experto.",
  "terapiaPareja.seo.description": "Terapia de pareja en Bogotá con Sandra Vargas, psicóloga con 38 años de experiencia. Enfoque sistémico y gestáltico. Fortalece tu relación, resuelve conflictos. Sesiones presenciales y online.",
  "terapiaPareja.seo.title": "Terapia de Pareja - Sandra Vargas Psicóloga Bogotá",
  "terapiaPareja.sessions.description": "Cada sesión de pareja tiene una duración de 120 minutos (2 horas), tiempo necesario para trabajar las dinámicas relacionales de forma profunda y efectiva.",
  "terapiaPareja.sessions.duration": "Duración: 120 minutos (2 horas)",
  "terapiaPareja.sessions.modality.online": "Online: Para parejas hispanohablantes en cualquier parte del mundo",
  "terapiaPareja.sessions.modality.presencial": "Presencial: Consultorio privado en Bogotá",
  "terapiaPareja.sessions.title": "¿Cómo son las sesiones de pareja?",
  "terapiaPareja.title": "Terapia de Pareja",
  "terapiaPareja.whenToSeek.title": "¿Cuándo buscar terapia de pareja?",
  "terapiaPareja.workWith.description": "Trabajo con parejas que enfrentan:\n\n• Dificultades de comunicación y conflictos recurrentes\n• Crisis de pareja o momentos de transición\n• Infidelidad o quiebre de confianza\n• Diferencias en expectativas o proyecto de vida\n• Problemas de intimidad emocional o sexual\n• Decisión de continuar o finalizar la relación",
  "terapiaPareja.workWith.title": "¿Con qué parejas trabajo?",
};

/**
 * Helper para obtener un texto por su clave
 * Si no existe, retorna un texto por defecto o la clave misma
 */
export const getText = (key: string, defaultText?: string): string => {
  return texts[key] || defaultText || key;
};

/**
 * Helper para verificar si existe un texto
 */
export const hasText = (key: string): boolean => {
  return key in texts;
};

export default texts;

